# Site settings
name: TO be or not to be
email: 312058125@qq.com
author: Marin
url: ""
resume_site: ""
github: https://github.com/itmanmzt/
baseurl: ""
description: Try your best!
meta_description: Marin的个人博客，一个自学编程的大三学生，在即将毕业的迷茫期，给自己一个证明自己的机会。
motto: no regrets.
banner: 让未来的你感谢现在拼命的自己。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: itmanmzt

# Build settings
markdown: kramdown

baidu_analysis: ""

